services:
  nsky-db:
    image: postgres:18
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - nsky
    environment:
      POSTGRES_DB: nsky
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - nsky-data:/var/lib/postgresql

networks:
  nsky:

volumes:
  nsky-data:
