CREATE TABLE "chat" (
    "id" bigint generated by default as identity,
    "name" varchar(255),
    primary key ("id")
);

CREATE TABLE "message" (
    "id" bigint generated by default as identity,
    "chat_id" bigint not null,
    "author" varchar(255),
    "content" varchar(255),
    primary key("id")
);

ALTER TABLE IF EXISTS "message"
    ADD CONSTRAINT "fk_message_chat"
        FOREIGN KEY("chat_id")
            REFERENCES "chat";